### ISSUE TITLE
(Mobil) Pull to refresh?

### ISSUE THREAD

**Issue by flashsharp** [randigtroja/Flashback#75]

**Comment by randigtroja** [comment]
Ja, det tycker jag är bra, men knapparna för refresh måste finnas kvar även om det läggs till. 

Vi ska isf använda oss av kontrollen som finns implementerad i "uwp conmunity toolkit" som vi redan har refererat och använder. 

Är lite osäker på om det var möjligt eller om det ens är bra att använda det på favoritsidan där vi nu har "swipe to delete".

Det var bara lite spontana tankar :)

**Comment by randigtroja** [comment]
@flashsharp 

jag har påbörjat denna nu
